# This is the default config. If you want to change something for a 
# particular instance, make a config-custom.yml in the same folder. 
features:
  hackyHourReminder:
    active: True
    location: Pasco
    time: 16
  nlprgReminder:
    active: True
    url: "https://raw.githubusercontent.com/wiki/clulab/nlp-reading-group/FALL-2017-Reading-Schedule.md"
    time: 10

# TODO Figure out how to get default behavior, esp for channels.
# make a default yml that is common to all versions, and an unversioned
# yml that overrides the defaults
channels:
  restricted: True
  allowed:
    - \#bottest