# This is the default config. If you want to change something for a 
# particular instance, make a config-custom.yml in the same folder. 
version: 1.0

features:
  passive:
    hackyHourReminder:
      active: True
      location: Pasco
      time: 16
    nlprgReminder:
      active: True
      url: "https://raw.githubusercontent.com/wiki/clulab/nlp-reading-group/Fall-2017-Reading-Schedule.md"
      time: 10
    genericReminder:
      active: True
      hoursBefore: 6
      filename: "generic_schedule.csv"
  active:
    meetingInfo:
      active: True
      command: "next"
      filename: "generic_schedule.csv"
    addEvent:
      active: True
      command: "add event"
      filename: "generic_schedule.csv"
    help:
      active: True
      command: "help"



# TODO Figure out how to get default behavior, esp for channels.
# make a default yml that is common to all versions, and an unversioned
# yml that overrides the defaults
channels:
  restricted: True
  allowed:
    - \#bottest
    - C25NW0WN7